version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /.github/actions/ci-setup
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      ci-setup-actions:
        patterns:
          - '*'
