
// Action types
export const INCREMENT_COUNTER  = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER  = 'DECREMENT_COUNTER'
export const INCREMENT_IF_ODD   = 'INCREMENT_IF_ODD'
export const INCREMENT_ASYNC    = 'INCREMENT_ASYNC'
export const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC'

export const SHOW_CONGRATULATION = 'SHOW_CONGRATULATION'
export const HIDE_CONGRATULATION = 'HIDE_CONGRATULATION'
